site_name: FinBrickLab
site_description: Strategy-Driven Brick Architecture for Financial Scenarios
repo_url: https://github.com/didac-crst/finbricklab
repo_name: didac-crst/finbricklab
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - content.code.copy
    - search.suggest
    - search.highlight

plugins:
  - search
  - autorefs
  - gen-files:
      scripts:
        - docs/gen_ref_nav.py
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google
            members_order: source
            show_source: true
            show_root_heading: true
            heading_level: 2
            merge_init_into_class: true
            separate_signature: true
            filters: ["!^_"]

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji
  - attr_list
  - tables

nav:
  - Home: index.md
  - Guides:
      - Examples: EXAMPLES.md
      - Strategies: STRATEGIES.md
      - Entity & Canonical Schema: ENTITY_AND_CANONICAL_SCHEMA.md
  - Reference:
      - Overview: reference/index.md
      - Core:
          - Bricks: reference/finbricklab/core/bricks.md
          - Scenario: reference/finbricklab/core/scenario.md
          - Entity: reference/finbricklab/core/entity.md
          - Context: reference/finbricklab/core/context.md
          - Results: reference/finbricklab/core/results.md
      - Strategies:
          - Valuation Cash: reference/finbricklab/strategies/valuation/cash.md
          - Valuation ETF: reference/finbricklab/strategies/valuation/etf_unitized.md
          - Valuation Property: reference/finbricklab/strategies/valuation/property_discrete.md
          - Flow Income: reference/finbricklab/strategies/flow/income.md
          - Flow Expense: reference/finbricklab/strategies/flow/expense.md
          - Flow Transfer: reference/finbricklab/strategies/flow/transfer.md
          - Schedule Mortgage: reference/finbricklab/strategies/schedule/mortgage_annuity.md
      - Utilities:
          - Charts: reference/finbricklab/charts.md
          - CLI: reference/finbricklab/cli.md
          - FX: reference/finbricklab/fx.md
          - KPI: reference/finbricklab/kpi.md
