name: docs
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - uses: abatilo/actions-poetry@v3
        with: { poetry-version: "1.8.3" }
      - run: poetry install --only docs
      - run: poetry run mkdocs build
      - run: poetry run interrogate -c pyproject.toml src/finbricklab
      - name: Upload site artifact (PR preview)
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - uses: abatilo/actions-poetry@v3
        with: { poetry-version: "1.8.3" }
      - run: poetry install --only docs
      - run: poetry run mkdocs build
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site
